[package]
name = "tree-sync"
version = "0.1.0"
edition = "2021"
authors = ["Plamadeala Mihai <plamadeala.mihai002@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"